/* DiMath.java */
/* Generated By:JavaCC: Do not edit this line. DiMath.java */
package arch.math.dimath.parser;

import arch.math.dimath.Lexeme;
import java.util.List;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Map;

/*
    (){}->0
    (){a}->a
    (x){}->x
    x->x
    x{a,b,c}->x*a+b/c
    x{a}->x+a
    (x,y,z)-> x*y*z
    ()->35
    ()->-45
    (){a:[0]}->a^2
    (){a:[0],b:4.87,c:[1],d:[2]}->b*a+c^d
    (x,y,z){a:1,b:2,c:3}->x^c+x*y+z^(a^sin(b))
 */

final class DiMath implements DiMathConstants {

    private final HashSet<String> identifiers;

    {
        this.identifiers = new HashSet<>();
    }

    private Lexeme lex(Lexeme.AbstractKind kind, Token tk){
        return new Lexeme(kind, tk.image);
    }

  final private void NumericLiteral(List<Lexeme> expr) throws ParseException {Token tk = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case int_lit:{
      tk = jj_consume_token(int_lit);
expr.add(lex(Lexeme.AbstractKind.INT_LIT,tk));
      break;
      }
    case float_lit:{
      tk = jj_consume_token(float_lit);
expr.add(lex(Lexeme.AbstractKind.FLOAT_LIT,tk));
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final private void Operator(List<Lexeme> expr) throws ParseException {Token tk = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case sum:{
      tk = jj_consume_token(sum);
expr.add(lex(Lexeme.AbstractKind.OPERATOR,tk));
      break;
      }
    case difference:{
      tk = jj_consume_token(difference);
expr.add(lex(Lexeme.AbstractKind.OPERATOR,tk));
      break;
      }
    case product:{
      tk = jj_consume_token(product);
expr.add(lex(Lexeme.AbstractKind.OPERATOR,tk));
      break;
      }
    case quotient:{
      tk = jj_consume_token(quotient);
expr.add(lex(Lexeme.AbstractKind.OPERATOR,tk));
      break;
      }
    case remainder:{
      tk = jj_consume_token(remainder);
expr.add(lex(Lexeme.AbstractKind.OPERATOR,tk));
      break;
      }
    case bitwise_xor:{
      tk = jj_consume_token(bitwise_xor);
expr.add(lex(Lexeme.AbstractKind.OPERATOR,tk));
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final private void FunctionReference(List<Lexeme> expr) throws ParseException {Token tk;
    tk = jj_consume_token(identifier);
expr.add(lex(Lexeme.AbstractKind.FUNCTION_REFERENCE,tk));
}

  final private void Argument(List<Lexeme> expr) throws ParseException {
    GroupedExpression(expr);
}

  final private void Call(List<Lexeme> expr) throws ParseException {
    FunctionReference(expr);
expr.add(new Lexeme(Lexeme.AbstractKind.OPERATOR,"<"));
    Argument(expr);
}

  final private void ParameterFactorReference(List<Lexeme> expr) throws ParseException {Token tk;
    tk = jj_consume_token(identifier);
expr.add(lex(Lexeme.AbstractKind.PARAMETER_FACTOR_REFERENCE,tk));
}

  final private void Operand(List<Lexeme> expr) throws ParseException {Token tk;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case int_lit:
    case float_lit:{
      NumericLiteral(expr);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      if (jj_2_1(2)) {
        Call(expr);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case left_parenthesis:{
          GroupedExpression(expr);
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          if (jj_2_2(2)) {
            ParameterFactorReference(expr);
          } else {
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    }
}

  final public void Expression(List<Lexeme> expr) throws ParseException {Token tk = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case sum:
    case difference:{
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case sum:{
          tk = jj_consume_token(sum);
          break;
          }
        case difference:{
          tk = jj_consume_token(difference);
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } finally {
expr.add(new Lexeme(Lexeme.AbstractKind.INT_LIT,"0"));
            expr.add(lex(Lexeme.AbstractKind.OPERATOR,tk));
      }
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    Operand(expr);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case sum:
      case difference:
      case product:
      case quotient:
      case remainder:
      case bitwise_xor:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_1;
      }
      Operator(expr);
      Operand(expr);
    }
}

  final private void GroupedExpression(List<Lexeme> expr) throws ParseException {Token tk;
    tk = jj_consume_token(left_parenthesis);
expr.add(lex(Lexeme.AbstractKind.LEFT_GROUPER,tk));
    Expression(expr);
    tk = jj_consume_token(right_parenthesis);
expr.add(lex(Lexeme.AbstractKind.RIGHT_GROUPER,tk));
}

  final private void ParameterBlock(List<Lexeme> parameters) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case identifier:{
      ParameterDeclaration(parameters);
      break;
      }
    case left_parenthesis:{
      jj_consume_token(left_parenthesis);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case identifier:{
        ParameterDeclaration(parameters);
        label_2:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case comma:{
            ;
            break;
            }
          default:
            jj_la1[7] = jj_gen;
            break label_2;
          }
          jj_consume_token(comma);
          ParameterDeclaration(parameters);
        }
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      jj_consume_token(right_parenthesis);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final private void ParameterDeclaration(List<Lexeme> parameters) throws ParseException {Token tk;
    tk = jj_consume_token(identifier);
parameters.add(lex(Lexeme.AbstractKind.PARAMETER_NAME,tk));
        identifiers.add(tk.image);
}

  final private void FactorBlock(Map<Lexeme,Lexeme> factors) throws ParseException {
    jj_consume_token(left_brace);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case identifier:{
      FactorDeclaration(factors);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case comma:{
          ;
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          break label_3;
        }
        jj_consume_token(comma);
        FactorDeclaration(factors);
      }
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(right_brace);
}

  final private void FactorDeclaration(Map<Lexeme,Lexeme> factors) throws ParseException {Token tk; Lexeme key, value = null;
    tk = jj_consume_token(identifier);
key = lex(Lexeme.AbstractKind.FACTOR_NAME,tk);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case colon:{
      jj_consume_token(colon);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case int_lit:{
        tk = jj_consume_token(int_lit);
value = lex(Lexeme.AbstractKind.INT_LIT, tk);
        break;
        }
      case float_lit:{
        tk = jj_consume_token(float_lit);
value = lex(Lexeme.AbstractKind.FLOAT_LIT, tk);
        break;
        }
      case left_bracket:{
        jj_consume_token(left_bracket);
        tk = jj_consume_token(int_lit);
value = lex(Lexeme.AbstractKind.INDEX_REFERENCE, tk);
        jj_consume_token(right_bracket);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
factors.put(key, value != null ? value : new Lexeme(Lexeme.AbstractKind.INT_LIT, "0"));
        identifiers.add(key.toString());
}

  final public void Signature(List<Lexeme> parameters, Map<Lexeme,Lexeme> factors) throws ParseException {
    ParameterBlock(parameters);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case left_brace:{
      FactorBlock(factors);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
}

  final public void Body(List<List<Lexeme>> exprMatrix) throws ParseException {List<Lexeme> expr;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case identifier:
    case sum:
    case difference:
    case left_parenthesis:
    case int_lit:
    case float_lit:{
      Expression(expr = new LinkedList<>());
exprMatrix.add(expr);
      break;
      }
    case left_brace:{
      jj_consume_token(left_brace);
      Expression(expr = new LinkedList<>());
exprMatrix.add(expr);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case comma:{
          ;
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          break label_4;
        }
        jj_consume_token(comma);
        Expression(expr = new LinkedList<>());
exprMatrix.add(expr);
      }
      jj_consume_token(right_brace);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void DiMathLambda(List<Lexeme> parameters, Map<Lexeme,Lexeme> factors, List<List<Lexeme>> exprMatrix) throws ParseException {
    Signature(parameters, factors);
    jj_consume_token(arrow);
    Body(exprMatrix);
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_3R_FunctionReference_136_5_7()
 {
    if (jj_scan_token(identifier)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_Call_144_5_5()) return true;
    return false;
  }

  private boolean jj_3R_Call_144_5_5()
 {
    if (jj_3R_FunctionReference_136_5_7()) return true;
    if (jj_3R_Argument_140_5_8()) return true;
    return false;
  }

  private boolean jj_3R_GroupedExpression_184_5_9()
 {
    if (jj_scan_token(left_parenthesis)) return true;
    return false;
  }

  private boolean jj_3R_Argument_140_5_8()
 {
    if (jj_3R_GroupedExpression_184_5_9()) return true;
    return false;
  }

  private boolean jj_3R_ParameterFactorReference_150_5_6()
 {
    if (jj_scan_token(identifier)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_ParameterFactorReference_150_5_6()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public DiMathTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[17];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x4000000,0xfc00,0x4000000,0x20000,0xc00,0xc00,0xfc00,0x100000,0x200,0x20200,0x100000,0x200,0x4040000,0x2000000,0x80000,0x100000,0x40a0e00,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x8,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x8,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public DiMath(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public DiMath(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new DiMathTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public DiMath(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new DiMathTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new DiMathTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public DiMath(DiMathTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(DiMathTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[41];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 17; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 41; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 2; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
