/* Generated By:JavaCC: Do not edit this line. DiMathConstants.java */
package arch.math.dimath.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DiMathConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int unicode_letter = 2;
  /** RegularExpression Id. */
  int unicode_digit = 3;
  /** RegularExpression Id. */
  int letter = 4;
  /** RegularExpression Id. */
  int decimal_digit = 5;
  /** RegularExpression Id. */
  int binary_digit = 6;
  /** RegularExpression Id. */
  int octal_digit = 7;
  /** RegularExpression Id. */
  int hex_digit = 8;
  /** RegularExpression Id. */
  int identifier = 9;
  /** RegularExpression Id. */
  int sum = 10;
  /** RegularExpression Id. */
  int difference = 11;
  /** RegularExpression Id. */
  int product = 12;
  /** RegularExpression Id. */
  int quotient = 13;
  /** RegularExpression Id. */
  int remainder = 14;
  /** RegularExpression Id. */
  int bitwise_xor = 15;
  /** RegularExpression Id. */
  int arrow = 16;
  /** RegularExpression Id. */
  int left_parenthesis = 17;
  /** RegularExpression Id. */
  int left_bracket = 18;
  /** RegularExpression Id. */
  int left_brace = 19;
  /** RegularExpression Id. */
  int comma = 20;
  /** RegularExpression Id. */
  int dot = 21;
  /** RegularExpression Id. */
  int right_parenthesis = 22;
  /** RegularExpression Id. */
  int right_bracket = 23;
  /** RegularExpression Id. */
  int right_brace = 24;
  /** RegularExpression Id. */
  int colon = 25;
  /** RegularExpression Id. */
  int int_lit = 26;
  /** RegularExpression Id. */
  int decimal_lit = 27;
  /** RegularExpression Id. */
  int binary_lit = 28;
  /** RegularExpression Id. */
  int octal_lit = 29;
  /** RegularExpression Id. */
  int hex_lit = 30;
  /** RegularExpression Id. */
  int decimal_digits = 31;
  /** RegularExpression Id. */
  int binary_digits = 32;
  /** RegularExpression Id. */
  int octal_digits = 33;
  /** RegularExpression Id. */
  int hex_digits = 34;
  /** RegularExpression Id. */
  int float_lit = 35;
  /** RegularExpression Id. */
  int decimal_float_lit = 36;
  /** RegularExpression Id. */
  int decimal_exponent = 37;
  /** RegularExpression Id. */
  int hex_float_lit = 38;
  /** RegularExpression Id. */
  int hex_mantissa = 39;
  /** RegularExpression Id. */
  int hex_exponent = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<unicode_letter>",
    "<unicode_digit>",
    "<letter>",
    "<decimal_digit>",
    "<binary_digit>",
    "<octal_digit>",
    "<hex_digit>",
    "<identifier>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"->\"",
    "\"(\"",
    "\"[\"",
    "\"{\"",
    "\",\"",
    "\".\"",
    "\")\"",
    "\"]\"",
    "\"}\"",
    "\":\"",
    "<int_lit>",
    "<decimal_lit>",
    "<binary_lit>",
    "<octal_lit>",
    "<hex_lit>",
    "<decimal_digits>",
    "<binary_digits>",
    "<octal_digits>",
    "<hex_digits>",
    "<float_lit>",
    "<decimal_float_lit>",
    "<decimal_exponent>",
    "<hex_float_lit>",
    "<hex_mantissa>",
    "<hex_exponent>",
  };

}
